---
title: "Targeting Based on Heterogeneous Treatment Effects"
author: "Jack Gang"
date: "3/15/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
header-includes: \usepackage{color}
graphics: yes
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, comment = NA, message = FALSE,
                      fig.width = 10, fig.height = 10, fig.align = "center")
```

## Overview

As in the previous assignment, I used customer-level data from the data base of a company that sells kitchenware, housewares, and specialty food products. I again used the October 2015 sample that contains records on 250,000 customers, and in addition I also used a sample from a similar catalog mailing in October 2016 that contains 125,000 records.

The following are the four goals I accomplished:

1. Predict incremental dollar spending that we can attribute to the catalog mailing. In particular, I predicted incremental dollar spending at the customer-level, based on all the features that capture past customer behavior.

2. Predict customer-level incremental profits due to targeting a customer (catalog mailing), and develop a targeting strategy.

3. Evaluate the predictive power and profitability of the targeting strategy. Compare different targeting strategies, based on different estimation methods or heuristics.

4. Evaluate the predictive power and profitability of the targeting strategy that was developed using the 2015 data in an implementation of the strategy in 2016. This evaluation allowed me to assess the strict external validity or transportability of the results. Using more straightforward language, it allowed me to assess if the fancy techniques that I used actually worked.

\newpage

### Summary of findings

In this analysis, the first key finding I realized was that predicting incremental dollar spending that we can attribute to treatment (CATE) is much tricker than just predicting spending, as we did in Assignment 6. The lift tables have much more error and the lift charts were much less cleanly monotonically increasing. The entire calculation is based on a difference in means rather than just a raw spending value, and this added additional complexity when it comes to prediction calculations and standard errors.

However, it was clear that out of OLS, LASSO, and causal forest, causal forest emerged as the winner when it came to predicting incremental spending based on targeting a customer. This makes sense, as by design, causal forest is a method that directly perdicts heterogeneous treatment effects. This contrasts the results in Assignment 6 (predicting just spending), were LASSO and elastic net were better predictors than the tree/forest model. That said, I attempted using an elastic net on top of LASSO with various alpha values, but I was not able to get a lift table or profits that improved upon the causal forest model, at least when testing the out-of-sample 2016 data.

Speaking of which, evaluating the predictive power and profitability of these targeting strategies using out-of-sample data did work, but the results were more noisy and somewhat less predictive than the in-sample 2015 results. This was to be expected; however, it was good to see that the predictive power we fitted in 2015 didn't completely disappear in 2016, but rather still allowed us to predict CATE fairly well, especially when using causal forest.

